### ISSUE TITLE
misnamed file

### ISSUE THREAD

**Issue by maodonovan** [Code4SA/municipal-data#86]
Trying to run  (in postgres)
\i '/data/municipal-data/sql/table_capital_labeled.sql' gets 2 errrors
1) LINE 14:   id serial;
2) relation "public.capital_labeled" does not exist

I think... 
'id_serial;' should be 'id_serial,' and
'capital_labeled'  should be 'capital_labels'

**Comment by jbothma** [comment]
1) Yup - thanks! Sorry about that.
2) Nope - that was because the CREATE TABLE failed.

For this to be useful you'll also need the facts table datasets - I can share them with you if you like. Eventually they'll be downloadable from the website.

To be sure, you don't need to get this site up and running to use the data - you can just use the API via the temporary URL https://data.municipalmoney.org.za/api/cubes for now - or are you forking to supply us with some cool pull requests? :)
